### ISSUE TITLE
太大的响应heroku上好像处理不了

### ISSUE THREAD

**Issue by walkerning** [BigData-LZSJ/risk-map#6]
**An issue of Heroku**
https://github.com/benoitc/gunicorn/issues/ 840
(不想reference它＝ ＝所以就空了个空格)

下面是错误的heroku log，error code H18:

```
heroku[router]: sock=backend at=error code=H18 desc="Server Request Interrupted" method=POST path="/ajax/idx_list/" host=riskmap.herokuapp.com request_id=e0f5b408-8b7d-4eb5-8b74-603e6b9a32b5 fwd="blabla" dyno=web.1 connect=25ms service=874ms status=503 bytes=225
```

[heroku h18 error code](https://devcenter.heroku.com/articles/error-codes#h18-server-request-interrupted)

我先部署在自己的vps上吧。。。

**Comment by walkerning** [comment]
@shenh10 好神奇。。今天早上随便merge到了master分支。。发现heroku能用了。。。

**Comment by walkerning** [comment]
@shenh10 没事。。。又不能用了。后悔没截图为证。。。灵异事件＝ ＝

**Comment by shenh10** [comment]
是双击的问题么

**Comment by walkerning** [comment]
不是... fetch idx_list不是失败了吗。。。有一次灵异的没有出现这个issue所说的错误＝ ＝
